
on: # Apenas aciona quando há push para o branch develop
  push:
    branches: [ "develop" ] # Monitora apenas o branch develop

# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven and Auto PR

jobs:
  build_and_create_pr: # Nome do job alterado para refletir o objetivo
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          # Para criar um PR, a action de checkout precisa buscar o histórico completo
          # e ter permissões para acessar os outros branches.
          # Isso é importante para a action de criação de PR funcionar corretamente.
          fetch-depth: 0

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Create Pull Request
        id: create_pr
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Merge develop into main"
          title: "Merge develop into main"
          body: "This PR merges the latest changes from the develop branch into main."
          base: main
          branch: auto-merge-develop-to-main
          committer: GitHub Actions <actions@github.com>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          always-create: true

      - name: Check for PR URL
              if: ${{ steps.create_pr.outputs.pull-request-url }}
              run: |
                echo "Pull Request criada: ${{ steps.create_pr.outputs.pull-request-url }}"
                echo "Pull Request número: ${{ steps.create_pr.outputs.pull-request-number }}"